# Generated by Django 2.0.8 on 2018-09-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifaccapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambient',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='tag',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='hour',
            field=models.TimeField(null=True),
        ),
    ]
