# Generated by Django 2.0.8 on 2018-09-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifaccapp', '0002_auto_20180925_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='hour',
            new_name='entryTime',
        ),
        migrations.AddField(
            model_name='schedule',
            name='exitTime',
            field=models.TimeField(null=True),
        ),
    ]
