# Generated by Django 2.0.8 on 2018-09-28 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifaccapp', '0003_auto_20180925_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambient',
            name='name',
            field=models.TextField(max_length=50, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.TextField(max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='person',
            name='registration',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='ambient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifaccapp.Ambient', verbose_name='Ambiente'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.TextField(choices=[('Domingo', 'Domingo'), ('Segunda-feira', 'Segunda-feira'), ('Terça-feira', 'Terça-feira'), ('Quarta-feira', 'Quarta-feira'), ('Quinta-feira', 'Quinta-feira'), ('Sexta-feira', 'Sexta-feira'), ('Sábado', 'Sábado')], max_length=50, null=True, verbose_name='Dia'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='entryTime',
            field=models.TimeField(null=True, verbose_name='Hora de entrada'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='exitTime',
            field=models.TimeField(null=True, verbose_name='Hora de saída'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifaccapp.Person', verbose_name='Pessoa'),
        ),
    ]
