# Generated by Django 2.0.8 on 2018-09-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifaccapp', '0004_auto_20180928_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambient',
            name='name',
            field=models.TextField(max_length=100, null=True, verbose_name='Nome'),
        ),
    ]
