# Generated by Django 2.0.8 on 2018-09-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifaccapp', '0005_auto_20180929_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambient',
            name='type',
            field=models.TextField(choices=[('Coordenação', 'Coordenação'), ('Sala', 'Sala'), ('Laboratório', 'Laboratório')], max_length=50, null=True, verbose_name='Tipo de ambiente'),
        ),
    ]
