# Generated by Django 2.0.8 on 2018-09-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifaccapp', '0006_ambient_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambient',
            name='ID',
            field=models.TextField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
