# Generated by Django 2.0.13 on 2022-06-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifaccapp', '0008_auto_20181022_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, null=True, verbose_name='Usuário')),
                ('password', models.CharField(max_length=50, null=True, verbose_name='Senha')),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, null=True, verbose_name='Usuário')),
                ('password', models.CharField(max_length=50, null=True, verbose_name='Senha')),
                ('confirmPassword', models.CharField(max_length=50, null=True, verbose_name='Confirmação de senha')),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='tag',
        ),
        migrations.AddField(
            model_name='person',
            name='rfidtag',
            field=models.CharField(max_length=100, null=True, verbose_name='Tag RFID'),
        ),
        migrations.AlterField(
            model_name='ambient',
            name='ID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ambient',
            name='IP',
            field=models.CharField(max_length=15, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='ambient',
            name='mask',
            field=models.CharField(max_length=15, null=True, verbose_name='Máscara'),
        ),
        migrations.AlterField(
            model_name='ambient',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome'),
        ),
    ]
